Tweak workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -120,29 +120,55 @@ jobs:
           path: playwright-report
           retention-days: 14
 
-      - name: Check out reports branch
-        uses: actions/checkout@v4
-        with:
-          ref: reports
-          path: reports-branch
-          fetch-depth: 0
-
       - name: Generate report name and URL
         id: report-id
         run: |
           name=$(date +"%Y-%m-%d-%H-%M-%S")
           echo "name=$name" >> $GITHUB_OUTPUT
-          echo "url=https://github-playground-test-reports.netlify.app/$name/" >> $GITHUB_OUTPUT
+          echo "url=https://swup.github.io/swup/$name/" >> $GITHUB_OUTPUT
 
-      - name: Copy html report and push reports branch
+      - name: Check out reports branch
+        uses: actions/checkout@v4
+        with:
+          ref: reports
+          path: test-report-branch
+          fetch-depth: 0
+
+      - name: Copy html report
         run: |
-          cp -r playwright-report reports-branch/reports/${{ steps.report-id.outputs.name }}
-          cd reports-branch
-          git config user.name github-actions
-          git config user.email github-actions@github.com
+          mkdir -p test-report-branch/reports/${{ steps.report-id.outputs.name }}
+          cp -r playwright-report test-report-branch/reports/${{ steps.report-id.outputs.name }}
+          cd test-report-branch
+
+      - name: Set git user
+        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Push html report
+        # try push-rebase-loop in case the workflow is run multiple times at the same time
+        timeout-minutes: 3
+        run: |
           git add reports
-          git commit -m "Create report ${{ steps.report-id.outputs.name }}"
-          git push
+          git commit -m "Workflow: add html report for run ${{ github.run_id }} (attempt: ${{ github.run_attempt }})"
+
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+
+      - name: Output report url
+        run: |
+          echo "::notice title=Published Playwright test rReport::${{ steps.report-id.outputs.url }}"
 
       - name: Create report comment
         id: report-summary
