Rebase before push

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -143,8 +143,19 @@ jobs:
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add reports
-          git commit -m "Workflow: add html report for run ${{ github.run_id }} (attempt: ${{ github.run_attempt }})"
-          git push
+          git commit -m "Add test report for run ${{ github.run_id }} (attempt: ${{ github.run_attempt }})"
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
 
       - name: Output report url
         run: |
